version: "3.8"

volumes:
  build_folder: null

services:
  mysqldb:
    build: ./db
    container_name: mysqldb
    env_file:
      - "./db/db.env"
    ports:
      - "3306:3306"

  backend1:
    build: ./backend
    container_name: backend1
    restart: always
    env_file:
      - "./backend-secret.env"
      - "./spring-source.env"
    environment:
      - SERVER_PORT=8080
    depends_on:
      - mysqldb
    ports:
      - "8080:8080"
    command: [ "java", "-jar", "/app.jar" ]

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - './testing/grafana:/var/lib/grafana'
    restart: always
    environment: # 이 설정을 통해 로그인하지 않고 grafana 접속 가능
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin # 사용자에게 Adimin 역할 부여
      - GF_AUTH_ANONYMOUS_ENABLED=true # 익명 접근 활성화
      - GF_AUTH_BASIC_ENABLED=false # 기본 인증 비활성화

  k6:
    image: grafana/k6:latest
    container_name: k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./testing/k6:/scripts
    extra_hosts:
      - "host.docker.internal:host-gateway" # 호스트와 연결(로컬테스트를 위함)
    command: [ "run", "/scripts/test_script1.js" ]

  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    restart: on-failure # 실패 시 재시작
